// Injects API keys from process.env or .env directly into index.html at build time.
// On Vercel: reads process.env → rewrites the <!-- ENV:START/END --> block in index.html.
// Locally: also reads .env file and writes config.js for the dev server.
const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const indexPath = path.join(__dirname, 'index.html');
const configPath = path.join(__dirname, 'config.js');

// Start with system/Vercel process.env
const envVars = { ...process.env };

// Overlay .env file values if present (local development)
if (fs.existsSync(envPath)) {
  const envText = fs.readFileSync(envPath, 'utf8');
  envText.split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) return;
    const key = trimmed.slice(0, eqIdx).trim();
    let val = trimmed.slice(eqIdx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    envVars[key] = val;
  });
}

const keys = {
  groq: envVars.GROQ_API_KEY || '',
  gemini: envVars.GEMINI_API_KEY || '',
  sarvam: envVars.SARVAM_API_KEY || ''
};

const firebaseConfig = {
  apiKey: envVars.FIREBASE_API_KEY || '',
  authDomain: envVars.FIREBASE_AUTH_DOMAIN || '',
  projectId: envVars.FIREBASE_PROJECT_ID || '',
  storageBucket: envVars.FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: envVars.FIREBASE_MESSAGING_SENDER_ID || '',
  appId: envVars.FIREBASE_APP_ID || '',
  measurementId: envVars.FIREBASE_MEASUREMENT_ID || ''
};

// ── 1. Inject keys into index.html (works on Vercel where config.js never gets served) ──
let html = fs.readFileSync(indexPath, 'utf8');

const inlineBlock = `<!-- ENV:START -->
<script>
window.ENV_KEYS = ${JSON.stringify(keys)};
window.ENV_FIREBASE = ${JSON.stringify(firebaseConfig)};
</script>
<!-- ENV:END -->`;

if (html.includes('<!-- ENV:START -->')) {
  html = html.replace(/<!-- ENV:START -->[\s\S]*?<!-- ENV:END -->/m, inlineBlock);
} else {
  html = html.replace('</head>', inlineBlock + '\n</head>');
}

fs.writeFileSync(indexPath, html);

// ── 2. Also write config.js for local dev server ──
const configOutput = `// AUTO-GENERATED BY sync-env.js — DO NOT COMMIT TO GIT
window.ENV_KEYS = ${JSON.stringify(keys, null, 2)};
window.ENV_FIREBASE = ${JSON.stringify(firebaseConfig, null, 2)};
`;
fs.writeFileSync(configPath, configOutput);

console.log('✓ index.html ENV block injected');
console.log('✓ config.js generated');
console.log('  Groq key present:', !!keys.groq);
console.log('  Firebase projectId:', firebaseConfig.projectId || '(none)');
